version: "2"

networks:
  default:
    ipam:
      config:
        - subnet: 172.32.0.0/16

services:

  node_server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    command: node /www/server.js
    networks:
      default:
        ipv4_address: 172.32.0.100

  rstudio:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/rstudio
      dockerfile: Dockerfile
    ports:
      - "3000:8888"
    networks:
      default:
        ipv4_address: 172.32.0.10
  
  spyder:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/spyder
      dockerfile: Dockerfile
    ports:
      - "3001:8888"
    networks:
      default:
        ipv4_address: 172.32.0.11
  
  git:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/git
      dockerfile: Dockerfile
    ports:
      - "3002:8888"
    networks:
      default:
        ipv4_address: 172.32.0.12

  jupyter:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/jupyter
      dockerfile: Dockerfile
    ports:
      - "3003:8888"
    networks:
      default:
        ipv4_address: 172.32.0.13
  
  orange:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/orange
      dockerfile: Dockerfile
    ports:
      - "3004:8888"
    networks:
      default:
        ipv4_address: 172.32.0.14

  vscode:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/vscode
      dockerfile: Dockerfile
    ports:
      - "3005:8888"
    networks:
      default:
        ipv4_address: 172.32.0.15

  markdown:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/markdown
      dockerfile: Dockerfile
    ports:
      - "3006:8888"
    networks:
      default:
        ipv4_address: 172.32.0.16

  hadoop:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/hadoop
      dockerfile: Dockerfile
    ports:
      - "3007:8888"
    networks:
      default:
        ipv4_address: 172.32.0.17

  spark:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/spark
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '3008:8888'
    networks:
      default:
        ipv4_address: 172.32.0.18
  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
