version: "2"

services:

  node_server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "80:8888"
    command: node /www/server.js
    
  rstudio:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/rstudio
      dockerfile: Dockerfile
    ports:
      - "3000:8888"
  
  spyder:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/spyder
      dockerfile: Dockerfile
    ports:
      - "3001:8888"
  
  git:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/git
      dockerfile: Dockerfile
    ports:
      - "3002:8888"

  jupyter:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/jupyter
      dockerfile: Dockerfile
    ports:
      - "3003:8888"
  
  orange:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/orange
      dockerfile: Dockerfile
    ports:
      - "3004:8888"

  vscpde:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/vscode
      dockerfile: Dockerfile
    ports:
      - "3005:8888"

  markdown:
    extends:
      file: compose-common.yml
      service: gui_app
    build:
      context: services/markdown
      dockerfile: Dockerfile
    ports:
      - "3006:8888"