version: "2"

networks:
  default:
    ipam:
      config:
        - subnet: 172.32.0.0/16

services:

  node_server:
    image: noah710/ml_toolkit:webserver
    ports:
      - "80:8080"
    command: node /www/server.js
    networks:
      default:
        ipv4_address: 172.32.0.100

  rstudio:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:rstudio
    ports:
      - "3000:8888"
    networks:
      default:
        ipv4_address: 172.32.0.10
  
  spyder:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:spyder
    ports:
      - "3001:8888"
    networks:
      default:
        ipv4_address: 172.32.0.11
  
  git:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:gitkraken
    ports:
      - "3002:8888"
    networks:
      default:
        ipv4_address: 172.32.0.12

  jupyter:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:jupyter
    ports:
      - "3003:8888"
    networks:
      default:
        ipv4_address: 172.32.0.13
  
  orange:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:orange
    ports:
      - "3004:8888"
    networks:
      default:
        ipv4_address: 172.32.0.14

  vscode:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:vscode
    ports:
      - "3005:8888"
    networks:
      default:
        ipv4_address: 172.32.0.15

  markdown:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:markdown
    ports:
      - "3006:8888"
    networks:
      default:
        ipv4_address: 172.32.0.16

  hadoop:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:hadoop
    ports:
      - "3007:8888"
    networks:
      default:
        ipv4_address: 172.32.0.17

  spark:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '3008:8888'
    networks:
      default:
        ipv4_address: 172.32.0.18
  spark-worker-1:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:3-debian-10
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  tensorflow:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:tensorflow
    ports:
      - "3009:8888"
    networks:
      default:
        ipv4_address: 172.32.0.19

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
  sonarscanner:
    extends:
      file: compose-common.yml
      service: gui_app
    image: noah710/ml_toolkit:sonarscanner
    volumes:
      - "./SHARED:/usr/src"
    depends_on: 
      - "sonarqube"
    ports:
      - "3010:8888"
    networks:
      default:
        ipv4_address: 172.32.0.20

  tableau:
    image: pvtmert/tableau
    privileged: true
    ports:
      - "8850:8850"
      - "8081:80"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"